const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="saimsamsun789@gmail.com"
global.location="Lahore,Pakistan."


global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://github.com/SuhailTechInfo/Suhail-Md/blob/main/lib/assets/suhail.jpg?raw=true" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "ᴘᴏᴡᴇʀᴇᴅ ʙʏ zᴀɪᴅ" 


global.devs = "923357433862" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923312705686";




//========================= [ BOT SETTINGS ] ======8===================\\
global.style = process.env.STYLE   || Math.floor(Math.random()*6) || '0'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || process.env.CAN_GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || process.env.CAN_WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "text" // "text" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "null" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "null,923xxxxxxxx";

global.api_smd = "https://api-smd.onrender.com" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID ||  "SUHAIL_10_21_07_30_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjQwLFxuICAgICAgICAyMjQsXG4gICAgICAgIDIyNCxcbiAgICAgICAgMTYzLFxuICAgICAgICA3OSxcbiAgICAgICAgMTc3LFxuICAgICAgICA5OSxcbiAgICAgICAgNzUsXG4gICAgICAgIDEyLFxuICAgICAgICAxMDIsXG4gICAgICAgIDIxMixcbiAgICAgICAgMjIwLFxuICAgICAgICAxNSxcbiAgICAgICAgMTg0LFxuICAgICAgICAxMzQsXG4gICAgICAgIDExMixcbiAgICAgICAgMjE5LFxuICAgICAgICAxNTQsXG4gICAgICAgIDU5LFxuICAgICAgICAyMTIsXG4gICAgICAgIDIxLFxuICAgICAgICAyMzIsXG4gICAgICAgIDUwLFxuICAgICAgICAxMDMsXG4gICAgICAgIDIwNSxcbiAgICAgICAgMTIyLFxuICAgICAgICAxODksXG4gICAgICAgIDE4NCxcbiAgICAgICAgMjQzLFxuICAgICAgICAxNjQsXG4gICAgICAgIDExOSxcbiAgICAgICAgODFcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTczLFxuICAgICAgICA3NCxcbiAgICAgICAgMTE2LFxuICAgICAgICAxMzQsXG4gICAgICAgIDI1MCxcbiAgICAgICAgMTAyLFxuICAgICAgICAxMTAsXG4gICAgICAgIDkzLFxuICAgICAgICA5MyxcbiAgICAgICAgMjcsXG4gICAgICAgIDg5LFxuICAgICAgICAyMDIsXG4gICAgICAgIDE0NyxcbiAgICAgICAgMjAyLFxuICAgICAgICA0OCxcbiAgICAgICAgMjAzLFxuICAgICAgICA5NSxcbiAgICAgICAgMTg5LFxuICAgICAgICAxOTQsXG4gICAgICAgIDI0MyxcbiAgICAgICAgNyxcbiAgICAgICAgMTYzLFxuICAgICAgICAyNCxcbiAgICAgICAgMzQsXG4gICAgICAgIDIwOSxcbiAgICAgICAgODksXG4gICAgICAgIDI0NyxcbiAgICAgICAgNTgsXG4gICAgICAgIDUxLFxuICAgICAgICA4NCxcbiAgICAgICAgMTY1LFxuICAgICAgICA4MVxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTIwLFxuICAgICAgICAzNixcbiAgICAgICAgMTMzLFxuICAgICAgICA1MCxcbiAgICAgICAgMTY1LFxuICAgICAgICA1NixcbiAgICAgICAgMjQ2LFxuICAgICAgICAxNTcsXG4gICAgICAgIDI5LFxuICAgICAgICAyMDUsXG4gICAgICAgIDQ3LFxuICAgICAgICAxMTUsXG4gICAgICAgIDgxLFxuICAgICAgICAxODQsXG4gICAgICAgIDE1NCxcbiAgICAgICAgMTg2LFxuICAgICAgICAxNCxcbiAgICAgICAgODYsXG4gICAgICAgIDQxLFxuICAgICAgICA0OCxcbiAgICAgICAgMTQxLFxuICAgICAgICAyMixcbiAgICAgICAgNDQsXG4gICAgICAgIDE3LFxuICAgICAgICAzLFxuICAgICAgICA4OSxcbiAgICAgICAgMTA4LFxuICAgICAgICA5NixcbiAgICAgICAgMjMyLFxuICAgICAgICA0OCxcbiAgICAgICAgMyxcbiAgICAgICAgNjhcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNzIsXG4gICAgICAgIDU4LFxuICAgICAgICA4OSxcbiAgICAgICAgNyxcbiAgICAgICAgMTM3LFxuICAgICAgICA0MCxcbiAgICAgICAgMTk0LFxuICAgICAgICAyMTMsXG4gICAgICAgIDEzMyxcbiAgICAgICAgNzIsXG4gICAgICAgIDcsXG4gICAgICAgIDEyNSxcbiAgICAgICAgOSxcbiAgICAgICAgOCxcbiAgICAgICAgMTE0LFxuICAgICAgICAxNTgsXG4gICAgICAgIDE2MyxcbiAgICAgICAgMjI3LFxuICAgICAgICAyLFxuICAgICAgICAxNjUsXG4gICAgICAgIDE1MSxcbiAgICAgICAgMTU3LFxuICAgICAgICAyMTEsXG4gICAgICAgIDk3LFxuICAgICAgICAxNjksXG4gICAgICAgIDEwMSxcbiAgICAgICAgMTIxLFxuICAgICAgICAxODcsXG4gICAgICAgIDE1NixcbiAgICAgICAgMjM5LFxuICAgICAgICAyNTQsXG4gICAgICAgIDcxXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyNDgsXG4gICAgICAgIDIxMixcbiAgICAgICAgMTk5LFxuICAgICAgICAyMzksXG4gICAgICAgIDE0MCxcbiAgICAgICAgMjM2LFxuICAgICAgICA2NCxcbiAgICAgICAgMTAsXG4gICAgICAgIDEyMCxcbiAgICAgICAgMTkyLFxuICAgICAgICAxNTUsXG4gICAgICAgIDcxLFxuICAgICAgICAyNDAsXG4gICAgICAgIDE1LFxuICAgICAgICAyMDksXG4gICAgICAgIDY0LFxuICAgICAgICAxNCxcbiAgICAgICAgMTY3LFxuICAgICAgICA4LFxuICAgICAgICA2MyxcbiAgICAgICAgMTE1LFxuICAgICAgICAxMTgsXG4gICAgICAgIDQ5LFxuICAgICAgICA0NSxcbiAgICAgICAgMjE0LFxuICAgICAgICA1MyxcbiAgICAgICAgNjUsXG4gICAgICAgIDE4MSxcbiAgICAgICAgMTMzLFxuICAgICAgICAxNixcbiAgICAgICAgMTI4LFxuICAgICAgICAxMThcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgODIsXG4gICAgICAgIDI4LFxuICAgICAgICAxNjksXG4gICAgICAgIDYxLFxuICAgICAgICA1LFxuICAgICAgICAxODAsXG4gICAgICAgIDcxLFxuICAgICAgICAxMTUsXG4gICAgICAgIDksXG4gICAgICAgIDE5MyxcbiAgICAgICAgMjQyLFxuICAgICAgICA0NixcbiAgICAgICAgMjE5LFxuICAgICAgICAxMTIsXG4gICAgICAgIDAsXG4gICAgICAgIDExMixcbiAgICAgICAgMTQzLFxuICAgICAgICAxNTEsXG4gICAgICAgIDE4MixcbiAgICAgICAgMTkwLFxuICAgICAgICAxMjAsXG4gICAgICAgIDE3OSxcbiAgICAgICAgNDMsXG4gICAgICAgIDEwNSxcbiAgICAgICAgNTQsXG4gICAgICAgIDE5MSxcbiAgICAgICAgMjE3LFxuICAgICAgICAyMjIsXG4gICAgICAgIDExMyxcbiAgICAgICAgMTMwLFxuICAgICAgICAyMjQsXG4gICAgICAgIDczXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDMyLFxuICAgICAgICAgIDE1OSxcbiAgICAgICAgICA2MCxcbiAgICAgICAgICAxMDQsXG4gICAgICAgICAgMTYxLFxuICAgICAgICAgIDIyMyxcbiAgICAgICAgICAxMDIsXG4gICAgICAgICAgMTQzLFxuICAgICAgICAgIDEwOSxcbiAgICAgICAgICAyNDIsXG4gICAgICAgICAgMjMzLFxuICAgICAgICAgIDI0NixcbiAgICAgICAgICAxNjMsXG4gICAgICAgICAgMTQzLFxuICAgICAgICAgIDEzMCxcbiAgICAgICAgICAxNTgsXG4gICAgICAgICAgMTU1LFxuICAgICAgICAgIDU2LFxuICAgICAgICAgIDMsXG4gICAgICAgICAgOTQsXG4gICAgICAgICAgNDksXG4gICAgICAgICAgMjIsXG4gICAgICAgICAgMTU1LFxuICAgICAgICAgIDE1LFxuICAgICAgICAgIDIyMyxcbiAgICAgICAgICA1NSxcbiAgICAgICAgICAxOSxcbiAgICAgICAgICA5MixcbiAgICAgICAgICA3OSxcbiAgICAgICAgICAzLFxuICAgICAgICAgIDE5MyxcbiAgICAgICAgICA5MVxuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA3NSxcbiAgICAgICAgICAyNTEsXG4gICAgICAgICAgMTcsXG4gICAgICAgICAgMTQzLFxuICAgICAgICAgIDE2NyxcbiAgICAgICAgICA2NixcbiAgICAgICAgICAxNDYsXG4gICAgICAgICAgMTQsXG4gICAgICAgICAgMjAwLFxuICAgICAgICAgIDEyNCxcbiAgICAgICAgICAyNDEsXG4gICAgICAgICAgODksXG4gICAgICAgICAgMzEsXG4gICAgICAgICAgNDQsXG4gICAgICAgICAgMTU0LFxuICAgICAgICAgIDU2LFxuICAgICAgICAgIDE4LFxuICAgICAgICAgIDQ3LFxuICAgICAgICAgIDE1OSxcbiAgICAgICAgICA3MCxcbiAgICAgICAgICAxMjgsXG4gICAgICAgICAgNzgsXG4gICAgICAgICAgNzYsXG4gICAgICAgICAgOSxcbiAgICAgICAgICA0MCxcbiAgICAgICAgICAxMTgsXG4gICAgICAgICAgMyxcbiAgICAgICAgICA5MixcbiAgICAgICAgICA0NSxcbiAgICAgICAgICAyMTYsXG4gICAgICAgICAgODMsXG4gICAgICAgICAgNVxuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIwNSxcbiAgICAgICAgMTc3LFxuICAgICAgICA1NixcbiAgICAgICAgMTA4LFxuICAgICAgICA4OSxcbiAgICAgICAgMjAzLFxuICAgICAgICAzMyxcbiAgICAgICAgMTQ1LFxuICAgICAgICAyMDAsXG4gICAgICAgIDE5LFxuICAgICAgICA3NCxcbiAgICAgICAgMTQ0LFxuICAgICAgICA5MSxcbiAgICAgICAgOTcsXG4gICAgICAgIDE3MCxcbiAgICAgICAgMTEzLFxuICAgICAgICA5NixcbiAgICAgICAgMjQyLFxuICAgICAgICAxNTEsXG4gICAgICAgIDIzNSxcbiAgICAgICAgMTI0LFxuICAgICAgICAyNDIsXG4gICAgICAgIDE1MyxcbiAgICAgICAgNDYsXG4gICAgICAgIDE0MixcbiAgICAgICAgMjUxLFxuICAgICAgICA0NSxcbiAgICAgICAgNzksXG4gICAgICAgIDE0LFxuICAgICAgICAxMjYsXG4gICAgICAgIDg4LFxuICAgICAgICAyNTAsXG4gICAgICAgIDQ0LFxuICAgICAgICA1OCxcbiAgICAgICAgNzksXG4gICAgICAgIDk0LFxuICAgICAgICA5MyxcbiAgICAgICAgMjMsXG4gICAgICAgIDg3LFxuICAgICAgICAzMSxcbiAgICAgICAgNjIsXG4gICAgICAgIDE5OCxcbiAgICAgICAgMTQ4LFxuICAgICAgICAyMzIsXG4gICAgICAgIDEwMSxcbiAgICAgICAgMCxcbiAgICAgICAgNDQsXG4gICAgICAgIDExNyxcbiAgICAgICAgMTAyLFxuICAgICAgICAxNzMsXG4gICAgICAgIDEyNCxcbiAgICAgICAgMTI3LFxuICAgICAgICAyMzMsXG4gICAgICAgIDE2MixcbiAgICAgICAgMTg0LFxuICAgICAgICAyNTAsXG4gICAgICAgIDIwNSxcbiAgICAgICAgODYsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMjI1LFxuICAgICAgICAxNzYsXG4gICAgICAgIDIzNyxcbiAgICAgICAgMjEsXG4gICAgICAgIDZcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDksXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwiM1dzdDVydzJDTmRnTkRnOUdKQ0d4dnhHUndwR01NdXBmR3NMcVUycmZRaz1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW1xuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCI5MjMzMTI3MDU2ODZAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIkE1MkJCMDQzRDExNTI1RjZFNUFBM0U5QkZEOTdBMTUwXCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcyMjMzNDg5MlxuICAgIH0sXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjkyMzMxMjcwNTY4NkBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiQjJCQjcxQTFBMkQ5QjEwREM3QThGQkQwRDM0MEYwMURcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzIyMzM0ODkyXG4gICAgfSxcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiOTIzMzEyNzA1Njg2QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCJDMjM0QjIyNzdCQkUwNzA5RUNDODVGNjg5OTM0NzdEQlwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjIzMzQ4OTZcbiAgICB9LFxuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCI5MjMzMTI3MDU2ODZAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIjFBQzUzOEFGMDZDM0U5MkQ2NENDNTc1RDgxNTg1MkNCXCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcyMjMzNDg5NlxuICAgIH1cbiAgXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDEsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCJpaVJLVEM0UVNCZW9yTU1HNEM1elV3XCIsXG4gIFwicGhvbmVJZFwiOiBcImY4MmY3NTZiLTM4M2YtNGU2ZS1hMTgwLTc2ZmNlMTY5Y2Q4Y1wiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAxMzgsXG4gICAgICAyMDAsXG4gICAgICAxMDcsXG4gICAgICAxOTAsXG4gICAgICAzNSxcbiAgICAgIDEwNSxcbiAgICAgIDMwLFxuICAgICAgMTAyLFxuICAgICAgMjA5LFxuICAgICAgODMsXG4gICAgICAxNTksXG4gICAgICAxODUsXG4gICAgICA2MCxcbiAgICAgIDE1NCxcbiAgICAgIDI1MCxcbiAgICAgIDIyNixcbiAgICAgIDEzNCxcbiAgICAgIDc0LFxuICAgICAgMjYsXG4gICAgICAxMDlcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiB0cnVlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTE2LFxuICAgICAgNDEsXG4gICAgICA4OSxcbiAgICAgIDEsXG4gICAgICAyMjgsXG4gICAgICAxMTQsXG4gICAgICAxODAsXG4gICAgICAzOCxcbiAgICAgIDI2LFxuICAgICAgMjcsXG4gICAgICA3NyxcbiAgICAgIDI3LFxuICAgICAgMzIsXG4gICAgICAxNjcsXG4gICAgICAzNyxcbiAgICAgIDMyLFxuICAgICAgODEsXG4gICAgICAyMTQsXG4gICAgICAxNjksXG4gICAgICAxNjBcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcInBhaXJpbmdDb2RlXCI6IFwiSFNRQ1BBNDZcIixcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjkyMzMxMjcwNTY4NjoxMkBzLndoYXRzYXBwLm5ldFwiLFxuICAgIFwibmFtZVwiOiBcIkJBU0lUIEFMSVwiLFxuICAgIFwibGlkXCI6IFwiMTY0MTU4MzY0NTA0MjYxOjEyQGxpZFwiXG4gIH0sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ04yWHd2QURFS2Y5b3JVR0dBRWdBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwiQTlYRkpZMUk1R0tLbVYwSzcyc1lRUXgwUC9sWkV2Sjd4RVJ5eWhseWlERT1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCI0blN3S2NJeDA3d3oyelBtei9iYjRvaExDWW1ieTNwK3VISUYrWFRlcmU0YVBHNmMrb0N6bVo0REJiODlKRDVFTFQwWkVldlpmRUxNNVNGYkhKWUtDQT09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCJlYm9TSkMwbGtWVUZBdmZsRGI5cTRqQjFMQTN3aGZhZkVOcTIwbUxwVjhOOW1rMi9VU1cxZWJ3WEVSZlBuSjRtUm45bDJ0cXRwM2xPODZVNVpFSkxDUT09XCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCI5MjMzMTI3MDU2ODY6MTJAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICAzLFxuICAgICAgICAgIDIxMyxcbiAgICAgICAgICAxOTcsXG4gICAgICAgICAgMzcsXG4gICAgICAgICAgMTQxLFxuICAgICAgICAgIDcyLFxuICAgICAgICAgIDIyOCxcbiAgICAgICAgICA5OCxcbiAgICAgICAgICAxMzgsXG4gICAgICAgICAgMTUzLFxuICAgICAgICAgIDkzLFxuICAgICAgICAgIDEwLFxuICAgICAgICAgIDIzOSxcbiAgICAgICAgICAxMDcsXG4gICAgICAgICAgMjQsXG4gICAgICAgICAgNjUsXG4gICAgICAgICAgMTIsXG4gICAgICAgICAgMTE2LFxuICAgICAgICAgIDYzLFxuICAgICAgICAgIDI0OSxcbiAgICAgICAgICA4OSxcbiAgICAgICAgICAxOCxcbiAgICAgICAgICAyNDIsXG4gICAgICAgICAgMTIzLFxuICAgICAgICAgIDE5NixcbiAgICAgICAgICA2OCxcbiAgICAgICAgICAxMTQsXG4gICAgICAgICAgMjAyLFxuICAgICAgICAgIDI1LFxuICAgICAgICAgIDExNCxcbiAgICAgICAgICAxMzYsXG4gICAgICAgICAgNDlcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH1cbiAgXSxcbiAgXCJwbGF0Zm9ybVwiOiBcInNtYmFcIixcbiAgXCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXBcIjogMTcyMjMzNDg5MCxcbiAgXCJteUFwcFN0YXRlS2V5SWRcIjogXCJBQUFBQVBjWVwiXG59IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBUGNZLmpzb24iOiAie1wia2V5RGF0YVwiOlwiTEJzbGtQTFc1NE93TUh3QW56dlNJVXp2VEZYYlFzVkRlczV2cVNTQjFkWT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMDQxMjcxNzczLFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MjIzMzQ4OTEzODFcIn0iCn0="  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.3.8",
  caption : global.caption || "" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ zᴀɪᴅ 』```", 
 
  author : process.env.PACK_AUTHER|| "",
  packname: process.env.PACK_NAME || "",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "BASIT SINDHI",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "private",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
